networks:
  default:
    external: true
    name: mechanoidstore

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:

services:
# docker run -d --name mongodb --network=mechanoidstore mongodb:v1
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    # networks:
    # - mechanoidstore

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    volumes:
      - source: mongodb
        target: /data/db
        type: volume
    depends_on:
    - mongodb
    # networks:
    # - mechanoidstore

  web:
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment

  redis:
    image: redis
    container_name: redis
    volumes:
      - source: redis
        target: /data
        type: volume

  user:
    image: user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb

  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis

  mysql:
    image: mysql:v1
    container_name: mysql
    volumes:
      - source: mysql
        target: /var/lib/mysql
        type: volume

  shipping:
    image: shipping:v1
    container_name: shipping
    depends_on:
    - cart
    - mysql

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
      - source: rabbitmq
        target: /var/lib/rabbitmq
        type: volume
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123

  payment:
    image: payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
    - user
    - cart