networks:
  default:
    external: true
    name: mechanoidstore

services:
# docker run -d --name mongodb --network=mechanoidstore mongodb:1
  mongodb:
    image: mongodb:1
    container_name: mongodb
    # networks:
    # - mechanoidstore

  catalogue:
    image: catalogue:1
    container_name: catalogue
    depends_on:
    - mongodb
    # networks:
    # - mechanoidstore

  web:
    image: web:1
    container_name: web
    ports:
      - "80:80"
    depends_on:
    - catalogue

  redis:
    image: redis
    container_name: redis

  user:
    image: user:1
    container_name: user
    depends_on:
    - redis
    - mongodb

  cart:
    image: cart:1
    container_name: cart
    depends_on:
    - catalogue
    - redis

  mysql:
    image: mysql:1
    container_name: mysql

  shipping:
    image: shipping:1
    container_name: shipping
    depends_on:
    - cart
    - mysql

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123